// <auto-generated />
namespace SoloProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GetWcfWorking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GetWcfWorking));
        
        string IMigrationMetadata.Id
        {
            get { return "201701061203168_GetWcfWorking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
